INSERT INTO interviewer(id, name, avatar) VALUE (1,"Sylvia Palmer", "https://i.imgur.com/LpaY82x.png")
INSERT INTO interviewer(id, name, avatar) VALUE (2,"Tori Malcolm", "https://i.imgur.com/Nmx0Qxo.png")
INSERT INTO interviewer(id, name, avatar) VALUE (3,"Mildred Nazir", "https://i.imgur.com/T2WwVfS.png")
INSERT INTO interviewer(id, name, avatar) VALUE (4,"Cohana Roy", "https://i.imgur.com/FK8V841.jpg")
INSERT INTO interviewer(id, name, avatar) VALUE (5,"Sven Jones", "https://i.imgur.com/twYrpay.jpg")