INSERT INTO interviewer( name, avatar) VALUE ("Sylvia Palmer,"https://i.imgur.com/LpaY82x.png")
INSERT INTO interviewer( name, avatar) VALUE ("Tori Malcolm", "https://i.imgur.com/Nmx0Qxo.png")
INSERT INTO interviewer( name, avatar) VALUE ("Mildred Nazir", "https://i.imgur.com/T2WwVfS.png")
INSERT INTO interviewer( name, avatar) VALUE ("Cohana Roy", "https://i.imgur.com/FK8V841.jpg")
INSERT INTO interviewer( name, avatar) VALUE ("Sven Jones", "https://i.imgur.com/twYrpay.jpg")